name: Workflow Generator

on:
  push:
    branches: [ main, master ]
    paths:
      - '.github/workflows/workflow-generator.yml'
  workflow_dispatch:

jobs:
  generate-workflow:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      workflows: write  # This is the crucial missing permission

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate random workflow
        id: generate
        run: |
          mkdir -p .github/workflows
          RANDOM_NAME=$(head /dev/urandom | tr -dc a-z0-9 | head -c8)
          FILENAME=".github/workflows/${RANDOM_NAME}.yml"
          
          cat <<EOF > $FILENAME
          name: Generated Workflow - $RANDOM_NAME
          
          on:
            workflow_dispatch:
          
          jobs:
            test:
              runs-on: ubuntu-latest
              steps:
                - run: echo "Success! This workflow was auto-generated"
          EOF
          
          echo "filename=$FILENAME" >> $GITHUB_OUTPUT
          echo "Generated: $FILENAME"

      - name: Commit and push
        if: steps.generate.outputs.filename
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add .github/workflows/
          git commit -m "Add generated workflow: $(basename ${{ steps.generate.outputs.filename }})"
          git push origin HEAD:main
