name: Auto-create workflow file

on:
  push:
    branches: [ "main" ]
    paths:
      - '.github/workflows/auto-create.yml'

jobs:
  create-random-workflow:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Generate random workflow
        run: |
          # Create workflows directory if it doesn't exist
          mkdir -p .github/workflows
          
          # Generate random filename (8 random characters)
          RANDOM_NAME=$(head /dev/urandom | tr -dc a-z0-9 | head -c8)
          FILENAME=".github/workflows/${RANDOM_NAME}.yml"
          
          # Basic workflow content
          cat <<EOF > $FILENAME
          name: Random workflow ${RANDOM_NAME}
          
          on:
            workflow_dispatch:
            
          jobs:
            hello-world:
              runs-on: ubuntu-latest
              steps:
                - run: echo "Hello from randomly generated workflow!"
          EOF
          
          echo "Created new workflow file: $FILENAME"

      - name: Commit and push
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add .github/workflows/
          git commit -m "Auto-generated new workflow file"
          git push
