name: Workflow Generator

on:
  push:
    branches: [main]
    paths:
      - '.github/workflows/workflow-generator.yml'
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      workflows: write
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate workflow
        run: |
          mkdir -p .github/workflows
          RAND=$(date +%s | sha256sum | base64 | head -c 8)
          FILE=".github/workflows/generated-$RAND.yml"
          
          cat <<EOF > $FILE
          name: Generated Workflow
          on: [workflow_dispatch]
          jobs:
            test:
              runs-on: ubuntu-latest
              steps:
                - run: echo "This workflow was generated automatically"
          EOF
          
          echo "Generated $FILE"

      - name: Commit
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add .github/workflows/
          git commit -m "Add generated workflow" || echo "No changes to commit"
          git push || echo "Nothing to push"
